/* @file resource.h

    Generated by M$, consumed by RC.
    SPDX-License-Identifier: WTFPL

*/

#define IDD_CONTROL_PANEL_DIALOG        102
#define IDR_MAINFRAME                   128
#define ID_LIST_RIGHTCLICK_MENU         130
#define IDD_ADJUST_DIALOG               131
#define IDD_ABOUT_DIALOG                133
#define IDC_PANEL_LIST                  1000
#define IDC_ABOUT_BUTTON                1001
#define IDC_OVERALL_DESC                1002
#define IDC_SLIDER1                     1003
#define IDC_EDIT1                       1004
#define IDC_CHANNEL_COMBO               1005
#define IDC_ADJUST_HINT                 1006
#define ID_ECGM_LOGO                    1007
#define IDC_DESC                        1008
#define ID_CALIBRATE_MENU               32772
#define ID_MENU01_CALIBRATE             32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
